version: "3.7"

services:
  {{SERVICE.MAIL_RECEIVE.NAME}}:
    build: .
    container_name: {{SERVICE.MAIL_RECEIVE.NAME}}
    hostname: {{SERVICE.MAIL_RECEIVE.NAME}}.{{SERVER.DOMAIN}}
    restart: always
    ports:
      - {{SERVICE.MAIL_RECEIVE.PORTS.PORT_EXPOSED_IMAPS}}:993
    networks:
      - {{SERVICE.NETWORK.NAME}}
    volumes:
      - {{SERVER.CERTIFICATION.CERTIFICATES}}:/certificates
      - {{SERVER.SERVER_HOME}}/Server/Dovecot/Maildir:/maildir
      - {{SERVER.SERVER_HOME}}/Server/Dovecot/VMail:/usr/local/vmail
      - {{SERVER.SERVER_HOME}}/Server/Dovecot/Masters:/etc/dovecot/masters
      - {{SERVER.SERVER_HOME}}/Server/Dovecot/Log:/var/log/dovecot
      - {{SERVER.SERVER_HOME}}/Server/Dovecot/Sieve:/sieve

networks:
  {{SERVICE.NETWORK.NAME}}:
    external: true
